"""Narrow TRIAL-SBX contracts and generic closed-sandbox verification.

The package intentionally does not export the private pre-freeze canonical admission
function or bootstrap bytes. Generic verification grants no execution authority.
"""

from datetime import datetime

from .audit import (
    TrialAuditError,
    TrialAuditRecord,
    export_audit_bundle,
    verify_audit_bundle,
)
from .bundle import (
    TrialBundleError,
    TrialExecutionInputs,
    VerifiedTrialBundle,
    _AuthenticatedCanonicalAdmission,
    _register_environment_provenance,
    begin_trial_attempt,
    verify_input_bundle,
)
from .case_pack import (
    CANONICAL_TRIAL_CASE_PACK,
    TrialCanonicalCase,
    TrialCanonicalCaseAdmission,
    TrialCanonicalCasePack,
    TrialCaseAcceptance,
    TrialCaseExpectation,
    TrialCasePackError,
    TrialCasePackRun,
    TrialCasePolarity,
    TrialCaseReplayRecord,
    TrialDeferredFixture,
    TrialReplayPlan,
    run_canonical_case_pack,
)
from .contracts import (
    TRIAL_HARD_CAPS,
    TRIAL_STOP_PRECEDENCE,
    TrialAcceptanceOracle,
    TrialAcceptanceOraclePayload,
    TrialAdapterLane,
    TrialAdmissionStatus,
    TrialArtifactRef,
    TrialAttemptReceipt,
    TrialAttemptReceiptPayload,
    TrialAuditExportStatus,
    TrialCanonicalAdmission,
    TrialCanonicalAdmissionPayload,
    TrialCanonicalAdmissionStatus,
    TrialCanonicalPurpose,
    TrialCapabilityAcceptance,
    TrialCleanupDisposition,
    TrialContractError,
    TrialDataClass,
    TrialDocumentKind,
    TrialEnvironmentAdmission,
    TrialEnvironmentAdmissionPayload,
    TrialHardCaps,
    TrialInputBundleReceipt,
    TrialInputBundleReceiptPayload,
    TrialInputFileReceipt,
    TrialManifest,
    TrialManifestPayload,
    TrialMockOutputFixture,
    TrialMockOutputFixturePayload,
    TrialNamedHash,
    TrialOutcome,
    TrialResourceLimits,
    TrialResult,
    TrialResultPayload,
    TrialRuntimePosition,
    TrialRuntimeStep,
    TrialRuntimeStepPayload,
    TrialStop,
    TrialStopCondition,
    TrialStopPayload,
    TrialStopPhase,
    assert_environment_admission_binding,
    assert_trial_result_binding,
    freeze_trial_acceptance_oracle,
    freeze_trial_attempt_receipt,
    freeze_trial_canonical_admission,
    freeze_trial_environment_admission,
    freeze_trial_input_bundle_receipt,
    freeze_trial_manifest,
    freeze_trial_mock_output_fixture,
    freeze_trial_result,
    freeze_trial_runtime_step,
    freeze_trial_stop,
    select_controlling_stop,
    stop_outcome_for,
)
from .environment import (
    TrialEnvironmentError,
    TrialEnvironmentFacts,
)
from .environment import (
    evaluate_environment_admission as _evaluate_environment_admission,
)
from .full_function import (
    FullFunctionTrialError,
    FullFunctionTrialResult,
    run_full_function_trial,
)
from .integrated_chain import (
    InstalledApplicationChainError,
    InstalledApplicationChainReceipt,
    exercise_installed_application_chain,
)
from .rehearsal import (
    TrialInstalledRehearsalReceipt,
    TrialRehearsalError,
    run_installed_rehearsal,
)


def evaluate_environment_admission(
    *,
    attempt: TrialAttemptReceipt,
    manifest: TrialManifest,
    canonical_admission: TrialCanonicalAdmission | _AuthenticatedCanonicalAdmission,
    facts: TrialEnvironmentFacts,
    admission_id: str,
    frozen_at: datetime,
) -> TrialEnvironmentAdmission:
    """Evaluate and authenticate the exact package-entrypoint Environment record."""

    environment = _evaluate_environment_admission(
        attempt=attempt,
        manifest=manifest,
        canonical_admission=canonical_admission,
        facts=facts,
        admission_id=admission_id,
        frozen_at=frozen_at,
    )
    if environment.status is TrialAdmissionStatus.PASS and isinstance(
        canonical_admission, _AuthenticatedCanonicalAdmission
    ):
        _register_environment_provenance(environment, canonical_admission)
    return environment


__all__ = [
    "TRIAL_HARD_CAPS",
    "TRIAL_STOP_PRECEDENCE",
    "CANONICAL_TRIAL_CASE_PACK",
    "TrialAcceptanceOracle",
    "TrialAcceptanceOraclePayload",
    "TrialAdapterLane",
    "TrialAdmissionStatus",
    "TrialArtifactRef",
    "TrialAttemptReceipt",
    "TrialAttemptReceiptPayload",
    "TrialAuditError",
    "TrialAuditExportStatus",
    "TrialAuditRecord",
    "TrialBundleError",
    "TrialCanonicalCase",
    "TrialCanonicalCaseAdmission",
    "TrialCanonicalCasePack",
    "TrialCanonicalAdmission",
    "TrialCanonicalAdmissionPayload",
    "TrialCanonicalAdmissionStatus",
    "TrialCanonicalPurpose",
    "TrialCapabilityAcceptance",
    "TrialCaseAcceptance",
    "TrialCaseExpectation",
    "TrialCasePackError",
    "TrialCasePackRun",
    "TrialCasePolarity",
    "TrialCaseReplayRecord",
    "TrialDeferredFixture",
    "TrialCleanupDisposition",
    "TrialContractError",
    "TrialDataClass",
    "TrialDocumentKind",
    "TrialEnvironmentAdmission",
    "TrialEnvironmentAdmissionPayload",
    "TrialEnvironmentError",
    "TrialEnvironmentFacts",
    "TrialExecutionInputs",
    "TrialHardCaps",
    "TrialInputBundleReceipt",
    "TrialInputBundleReceiptPayload",
    "TrialInputFileReceipt",
    "InstalledApplicationChainError",
    "InstalledApplicationChainReceipt",
    "FullFunctionTrialError",
    "FullFunctionTrialResult",
    "TrialInstalledRehearsalReceipt",
    "TrialManifest",
    "TrialManifestPayload",
    "TrialMockOutputFixture",
    "TrialMockOutputFixturePayload",
    "TrialNamedHash",
    "TrialOutcome",
    "TrialResourceLimits",
    "TrialReplayPlan",
    "TrialRehearsalError",
    "TrialResult",
    "TrialResultPayload",
    "TrialRuntimePosition",
    "TrialRuntimeStep",
    "TrialRuntimeStepPayload",
    "TrialStop",
    "TrialStopCondition",
    "TrialStopPayload",
    "TrialStopPhase",
    "VerifiedTrialBundle",
    "assert_environment_admission_binding",
    "assert_trial_result_binding",
    "begin_trial_attempt",
    "evaluate_environment_admission",
    "exercise_installed_application_chain",
    "export_audit_bundle",
    "freeze_trial_acceptance_oracle",
    "freeze_trial_attempt_receipt",
    "freeze_trial_canonical_admission",
    "freeze_trial_environment_admission",
    "freeze_trial_input_bundle_receipt",
    "freeze_trial_manifest",
    "freeze_trial_mock_output_fixture",
    "freeze_trial_result",
    "freeze_trial_runtime_step",
    "freeze_trial_stop",
    "run_canonical_case_pack",
    "run_installed_rehearsal",
    "run_full_function_trial",
    "select_controlling_stop",
    "stop_outcome_for",
    "verify_audit_bundle",
    "verify_input_bundle",
]
